version: "2"
services:
  app:
    build: .
    command: bundle exec middleman server --bind-address=0.0.0.0
    ports:
      - '4567:4567'
    volumes:
      - .:/app
    volumes_from:
      - bundled_gems
  bundled_gems:
    image: busybox
    volumes:
      - /bundled_gems
